### ISSUE TITLE
Making a google login system by firebase and android studio

### ISSUE THREAD

**Issue by soumyajit1729** [soumyajit1729/Smart-Teaching#1]

**Comment by avivijay19** [comment]
Sir,
Wanted to work on this issue could you pls again this issue?

as well as my api key will be public if I work this project

**Comment by soumyajit1729** [comment]
hi, I am glad to know that you are interested. You can open a new Gmail account for this project only and share the password with me and use its firebase account. no need to use your own Gmail account. Feel free to join our slack channel and ask for further doubts.

**Comment by avivijay19** [comment]
okay, 
Thanks @soumyajit1729 sir
